services:
  backend:
    image: note-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: note-backend-prod
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: note-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: note-frontend-prod
    restart: always

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend
    restart: always
