services:
  backend-dev:
    image: note-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: note-backend-dev
    env_file:
      - ./backend/.env

  frontend-dev:
    image: note-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: note-frontend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend-dev
      - frontend-dev
