services:
  backend-dev:
    image: note-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    container_name: note-backend-dev
    env_file:
      - .env
