name: Deployment pipeline

on:
  push:
    branches:
      - ci/cd

jobs:
  backend-lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint backend
        run: npm run lint

  frontend-lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint frontend
        run: npm run lint

  backend-unit-tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Test backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test

  e2e-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Playwright Browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Start Backend and Frontend
        run: |
          cd backend && npm run start:test & # Start backend
          cd frontend && npm run dev & # Start frontend
          wait

      - name: Check Backend Server
        run: curl -v http://localhost:3001 || echo "Backend not reachable"

      - name: Check Frontend Server
        run: curl -v http://localhost:5173 || echo "Frontend not reachable"

      - name: E2E Tests
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          PORT: 3001
          SECRET: ${{ secrets.SECRET }}
          DEBUG: pw:* # Enable Playwright debug logs
        run: cd ./frontend && npm run test